repository_type: pipeline
lint:
  actions_ci: False
  files_exist:
    - conf/modules.config
  files_unchanged:
    - .gitattributes
    - .gitignore
  nextflow_config:
    - config_defaults:
      - params.bin_length
      - params.padding
      - params.scatter_content
