lint:
  actions_ci: false
  files_exist:
    - conf/modules.config
  files_unchanged:
    - .gitattributes
    - .gitignore
  modules_config: false
nf_core_version: 3.1.0
repository_type: pipeline
template:
  author: "@maxulysse"
  description: Generate Panel of Normals, models or other similar references from
    lots of samples
  force: false
  is_nfcore: true
  name: createpanelrefs
  org: nf-core
  outdir: .
  version: 1.0dev
