repository_type: pipeline
lint:
  actions_ci: False
  files_exist:
    - conf/modules.config
  files_unchanged:
    - .gitattributes
    - .gitignore
    - assets/nf-core-createpanelrefs_logo_light.png
    - docs/images/nf-core-createpanelrefs_logo_dark.png
    - docs/images/nf-core-createpanelrefs_logo_light.png
  nextflow_config:
    - config_defaults:
        - params.bin_length
        - params.padding
        - params.scatter_content
