<<<<<<< HEAD:modules/nf-core/fastqc/environment.yml
=======
name: gatk4_mutect2
>>>>>>> dev:modules/nf-core/gatk4/mutect2/environment.yml
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::gatk4=4.5.0.0
